name: ViaVersion
main: us.myles.ViaVersion.GlowstonePlugin
authors: [_MylesC, Matsv]
version: ${project.version}
description: ${project.description}
load: postworld
loadbefore: [ProtocolLib, ProxyPipe, SpigotLib, SkinRestorer]
softdepend: [ProtocolSupport, PacketListenerApi]
commands:
  viaversion:
    description: Shows ViaVersion Version and more.
    aliases: [viaver, vvglowstone]